# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-08 16:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='tested_buttons_ammount',
            new_name='tested_buttons_amount',
        ),
    ]
